DESTINATIONS = [
    {
        "name": "Everest Base Camp",
        "region": "Eastern",
        "daily_cost": 110,
        "lat": 27.9881,
        "lng": 86.9250,
        "image_url": "/app/images/Everest.jpg",
        "interests": ["mountains", "trekking", "adventure"],
        "best_for": ["iconic_trek", "challenging_trip"],
        "season": ["spring", "autumn"],
        "description": "A legendary Himalayan trek with unforgettable glacier views.",
    },
    {
        "name": "Pokhara Lakeside",
        "region": "Western",
        "daily_cost": 80,
        "lat": 28.2096,
        "lng": 83.9856,
        "image_url": "/app/images/pokhara_image.jpg",
        "interests": ["culture", "nature", "relaxation"],
        "best_for": ["slow_travel", "scenic_views"],
        "season": ["spring", "summer", "autumn"],
        "description": "A lakeside escape framed by snow-capped mountains.",
    },
    {
        "name": "Chitwan Wild",
        "region": "Southern",
        "daily_cost": 70,
        "lat": 27.5291,
        "lng": 84.3542,
        "image_url": "/app/images/chitwan_image.jpg",
        "interests": ["wildlife", "nature", "jungle"],
        "best_for": ["wildlife", "nature_trip"],
        "season": ["spring", "autumn", "winter"],
        "description": "Jungle safaris and rich wildlife in Nepal's lowlands.",
    },
    {
        "name": "Annapurna Region",
        "region": "Western",
        "daily_cost": 100,
        "lat": 28.5968,
        "lng": 83.9303,
        "image_url": "/app/images/everest_camp_image.webp",
        "interests": ["mountains", "trekking", "adventure"],
        "best_for": ["high_country", "mountain_views"],
        "season": ["spring", "autumn"],
        "description": "A dramatic Himalayan range with sweeping mountain routes.",
    },
    {
        "name": "Mustang",
        "region": "Northern",
        "daily_cost": 95,
        "lat": 29.1980,
        "lng": 83.9282,
        "image_url": "/app/images/mustang_image.jpeg",
        "interests": ["mountains", "culture", "trekking"],
        "best_for": ["remote_trip", "open_skies"],
        "season": ["summer", "autumn"],
        "description": "An arid highland region with strong Tibetan heritage.",
    },
    {
        "name": "Ilam",
        "region": "Eastern",
        "daily_cost": 45,
        "lat": 26.9119,
        "lng": 87.9308,
        "image_url": "/app/images/ilam.jpg",
        "interests": ["culture", "nature", "slow_travel"],
        "best_for": ["tea_gardens", "peaceful_hills"],
        "season": ["spring", "autumn"],
        "description": "Tea gardens, cool hills, and a calm countryside rhythm.",
    },
    {
        "name": "Janakpur",
        "region": "Central",
        "daily_cost": 40,
        "lat": 26.7280,
        "lng": 85.9228,
        "image_url": "/app/images/janakpur.jpg",
        "interests": ["culture", "heritage", "history"],
        "best_for": ["heritage", "local_life"],
        "season": ["winter", "spring", "autumn"],
        "description": "Ancient temples and a rich Mithila cultural tradition.",
    },
    {
        "name": "Bardiya",
        "region": "Western",
        "daily_cost": 60,
        "lat": 28.3949,
        "lng": 81.1501,
        "image_url": "/app/images/lumbini_image.jpg",
        "interests": ["wildlife", "nature", "birding"],
        "best_for": ["wildlife", "nature_trip"],
        "season": ["winter", "spring", "autumn"],
        "description": "A protected park with rich birdlife and jungle landscapes.",
    },
    {
        "name": "Bandipur",
        "region": "Western",
        "daily_cost": 50,
        "lat": 27.9357,
        "lng": 84.4142,
        "image_url": "/app/images/pokhara.jpg",
        "interests": ["culture", "heritage", "mountains"],
        "best_for": ["hill_town", "history"],
        "season": ["spring", "autumn"],
        "description": "A classic hill town with heritage homes and mountain views.",
    },
    {
        "name": "Bhaktapur",
        "region": "Central",
        "daily_cost": 45,
        "lat": 27.6729,
        "lng": 85.4279,
        "image_url": "/app/images/bhaktapur_image.jpg",
        "interests": ["heritage", "culture", "photography"],
        "best_for": ["history", "short_visit"],
        "season": ["spring", "autumn", "winter"],
        "description": "Ancient temples, squares, and a beautifully preserved old town.",
    },
    {
        "name": "Patan Lalitpur",
        "region": "Central",
        "daily_cost": 55,
        "lat": 27.6698,
        "lng": 85.3234,
        "image_url": "/app/images/patan.jpg",
        "interests": ["culture", "heritage", "art"],
        "best_for": ["art", "heritage"],
        "season": ["spring", "autumn", "winter"],
        "description": "Temple courtyards, artisan workshops, and Newari heritage.",
    },
    {
        "name": "Nagarkot",
        "region": "Central",
        "daily_cost": 55,
        "lat": 27.7127,
        "lng": 85.5231,
        "image_url": "/app/images/nagarkot_image.jpeg",
        "interests": ["sunrise", "nature", "short_trip"],
        "best_for": ["weekend_trip", "scenic_views"],
        "season": ["spring", "autumn", "winter"],
        "description": "A nearby hill station for sunrise views and easy escapes.",
    },
    {
        "name": "Langtang Region",
        "region": "Central",
        "daily_cost": 100,
        "lat": 28.2144,
        "lng": 85.5565,
        "image_url": "/app/images/Everest.jpg",
        "interests": ["mountains", "trekking", "nature"],
        "best_for": ["quiet_trek", "mountain_views"],
        "season": ["spring", "autumn"],
        "description": "A quieter Himalayan trekking experience with valleys and ridges.",
    },
    {
        "name": "Palpa Tansen",
        "region": "Western",
        "daily_cost": 50,
        "lat": 27.8666,
        "lng": 83.5508,
        "image_url": "/app/images/palpa.jpg",
        "interests": ["culture", "history", "local_life"],
        "best_for": ["local_culture", "hills"],
        "season": ["spring", "autumn", "winter"],
        "description": "Historic hill town life with views, heritage, and warmth.",
    },
    {
        "name": "Manaslu Region",
        "region": "Western",
        "daily_cost": 105,
        "lat": 28.5496,
        "lng": 84.5584,
        "image_url": "/app/images/everest_camp_image.webp",
        "interests": ["mountains", "trekking", "remote_trip"],
        "best_for": ["remote_trek", "mountain_scenery"],
        "season": ["spring", "autumn"],
        "description": "A remote and dramatic Himalayan circuit with wide-open views.",
    },
    {
        "name": "Rara Lake",
        "region": "Western",
        "daily_cost": 90,
        "lat": 29.5205,
        "lng": 82.0900,
        "image_url": "/app/images/pokhara.jpg",
        "interests": ["nature", "remote", "lake"],
        "best_for": ["remote_nature", "lake_views"],
        "season": ["summer", "autumn"],
        "description": "A secluded alpine lake surrounded by wild mountain views.",
    },
    {
        "name": "Koshi Tappu",
        "region": "Eastern",
        "daily_cost": 60,
        "lat": 26.5833,
        "lng": 87.1667,
        "image_url": "/app/images/chitwan_image.jpg",
        "interests": ["wildlife", "birding", "nature"],
        "best_for": ["birding", "wildlife"],
        "season": ["winter", "spring", "autumn"],
        "description": "Wetland birds, wildlife, and quiet river landscapes.",
    },
    {
        "name": "Kanchenjunga Region",
        "region": "Eastern",
        "daily_cost": 115,
        "lat": 27.7027,
        "lng": 88.1475,
        "image_url": "/app/images/Everest.jpg",
        "interests": ["mountains", "trekking", "remote_trip"],
        "best_for": ["far_north_east", "remote_scenery"],
        "season": ["spring", "autumn"],
        "description": "Remote Himalayan scenery with an expansive and wild feel.",
    },
    {
        "name": "Kathmandu",
        "region": "Central",
        "daily_cost": 65,
        "lat": 27.7172,
        "lng": 85.3240,
        "image_url": "/app/images/ktm_image.jpeg",
        "interests": ["culture", "food", "heritage", "city"],
        "best_for": ["first_time", "history", "shopping"],
        "season": ["spring", "autumn", "winter"],
        "description": "Historic temples, lively streets, and rich local cuisine.",
    },
    {
        "name": "Lumbini",
        "region": "Southern",
        "daily_cost": 50,
        "lat": 27.4876,
        "lng": 83.2743,
        "image_url": "/app/images/lumbini_image.jpg",
        "interests": ["religion", "history", "peace"],
        "best_for": ["pilgrimage", "history"],
        "season": ["winter", "spring", "autumn"],
        "description": "Buddhist heritage and peaceful spiritual experiences.",
    },
]
