DESTINATIONS = [
    {
        "name": "Kathmandu",
        "region": "Central",
        "daily_cost": 65,
        "lat": 27.7172,
        "lng": 85.3240,
        "image_url": "/images/ktm_image.jpeg",
        "interests": ["culture", "food", "heritage", "city"],
        "best_for": ["first_time", "history", "shopping"],
        "season": ["spring", "autumn", "winter"],
        "description": "Historic temples, lively streets, and rich local cuisine.",
    },
    {
        "name": "Pokhara",
        "region": "Western",
        "daily_cost": 80,
        "lat": 28.2096,
        "lng": 83.9856,
        "image_url": "/images/pokhara_image.jpg",
        "interests": ["nature", "trekking", "lake", "relaxation"],
        "best_for": ["scenic_views", "adventure"],
        "season": ["spring", "autumn", "summer"],
        "description": "Mountain views, lakeside walks, and adventure activities.",
    },
    {
        "name": "Chitwan",
        "region": "Southern",
        "daily_cost": 70,
        "lat": 27.5291,
        "lng": 84.3542,
        "image_url": "/images/chitwan_image.jpg",
        "interests": ["wildlife", "nature", "jungle"],
        "best_for": ["wildlife", "family_trip"],
        "season": ["spring", "autumn", "winter"],
        "description": "Wildlife safari and jungle experiences in Nepal's plains.",
    },
    {
        "name": "Lumbini",
        "region": "Southern",
        "daily_cost": 50,
        "lat": 27.4876,
        "lng": 83.2743,
        "image_url": "/images/lumbini_image.jpg",
        "interests": ["religion", "history", "peace"],
        "best_for": ["pilgrimage", "history"],
        "season": ["winter", "spring", "autumn"],
        "description": "Buddhist heritage and peaceful spiritual experiences.",
    },
    {
        "name": "Mustang",
        "region": "Northern",
        "daily_cost": 95,
        "lat": 29.1980,
        "lng": 83.9282,
        "image_url": "/images/mustang_image.jpeg",
        "interests": ["trekking", "culture", "mountains"],
        "best_for": ["adventure", "remote_trip"],
        "season": ["summer", "autumn"],
        "description": "A remote Himalayan desert region with strong Tibetan culture.",
    },
    {
        "name": "Nagarkot",
        "region": "Central",
        "daily_cost": 55,
        "lat": 27.7127,
        "lng": 85.5231,
        "image_url": "/images/nagarkot_image.jpeg",
        "interests": ["sunrise", "nature", "short_trip"],
        "best_for": ["weekend_trip", "scenic_views"],
        "season": ["spring", "autumn", "winter"],
        "description": "A nearby hill station for sunrise views and relaxing breaks.",
    },
    {
        "name": "Everest Base Camp Region",
        "region": "Eastern",
        "daily_cost": 110,
        "lat": 27.9881,
        "lng": 86.9250,
        "image_url": "/images/everest_camp_image.webp",
        "interests": ["trekking", "mountains", "adventure"],
        "best_for": ["trekking", "challenging_trip"],
        "season": ["spring", "autumn"],
        "description": "High-altitude trails and iconic Himalayan scenery.",
    },
    {
        "name": "Bhaktapur",
        "region": "Central",
        "daily_cost": 45,
        "lat": 27.6729,
        "lng": 85.4279,
        "image_url": "/images/bhaktapur_image.jpg",
        "interests": ["heritage", "culture", "photography"],
        "best_for": ["history", "short_visit"],
        "season": ["spring", "autumn", "winter"],
        "description": "Ancient temples, squares, and a beautifully preserved old town.",
    },
]
